### ISSUE TITLE
I'm getting We received a bad request trying to sign in

### ISSUE THREAD

**Issue by parclarke** [OfficeDev/SP-AngularJS-ExpenseManager-Code-Sample#2]
I'm getting "We received a bad request" trying to sign in. Any ideas of how I can resolve this?

**Comment by DanWahlin** [comment]
I'll have to look into that one - not sure I even finished that part off yet in the source. I'm tied up the remainder of this week but will look as soon as I can.

**Comment by DanWahlin** [comment]
Normally that means that something isn't configured right but it's really hard to say with only that info. I'd first make sure that your app is configured properly with Azure Active Directory (and if you saw another response from me ignore it - was referring to a different app :-)). This particular sample app isn't one that's easy to provide any help on due to the number of moving parts unfortunately. But, I'd start with making sure the app is configured properly.
